commands_description = [

    ("help", "help", "show all available commands with their descriptions"),
    ("hello", "hello", "greet the Lana bot"),
    ("close or exit", "close or exit", "close the Lana bot"),
    ("add-contact", "add-contact [name] [phone]",
     "add new contact or update existed with additional phone number"),
    ("all-contacts", "all-contacts", "show all contacts in the Address bot"),
    ("change-contact", "change-contact [name] [field] [old_value] [new_value]",
     "change contact's fields such as phone, email, name, birthday"),
    ("find-contact", "find-contact [name]", "show concrete contact's fields"),
    ("delete-contact", "delete-contact [name]",
     "delete concrete contact from the Address bot"),
    ("show-phone", "show-phone [name]", "show concrete contact's phones"),
    ("add-birthday",
     "add-birthday [name] [birthday_date]", "add contact's birthday"),
    ("show-birthday", "show-birthday [name]",
     "show concrete contact's birthday"),
    ("birthdays", "birthdays [quantity_of_days]",
     "show birthdays within pointed period of time"),
    ("add-email", "add-email [name] [email]", "add contact's emails"),
    ("show-email", "show-email [name]", "show concrete contact's emails"),
    ("change-email",
     "change-email [name] [old_email] [new_email]", "change contact's email"),
    ("delete-email", "delete-email [name] [email]",
     "delete contact's concrete email"),
    ("add-address", "add-address [name] [address]", "add contact's address"),
    ("show-address", "show-address [name]", "show concrete contact's address"),
    ("delete-address", "delete-address [name]", "delete contact's address"),
    ("add-note", "add-note [title] [content] [tags]",
     "add a new note with a title, content, and optional tags"),
    ("delete-note", "delete-note [title]", "delete a note by its title"),
    ("change-note", "change-note [title] [new_content] [new_tags]",
     "edit a note's content and/or tags by its title"),
    ("find-note-by-title",
     "find-note-by-title [title]", "find a note by its title"),
    ("find-note-by-tag",
     "find-note-by-tag [tag]", "find notes containing a specific tag"),
    ("show-all-notes", "show-all-notes", "display all notes stored in the system"),
]
